### ISSUE TITLE
Add .vscode to .npmignore

### ISSUE THREAD

**Issue by maoberlehner** [marvinhagemeister/xhr-mocklet#18]
You absolutely should add your `.vscode` directory to `.npmignore`. I've just opened the npm package for debugging and (I think) because I also use the Settings Sync plugin, now all of my settings are the same as yours (globally, not only in the packages directory) -.-

Btw. you should also delete your GitHub Token for the Gist – if you upload it to npm it is not secret anymore ;)

**Comment by marvinhagemeister** [comment]
Thanks for your report. It's true that the `.vscode` folder doesn't have to be included in the npm package. Would be great if you could file a bug over at the repo for `Settings Sync Plugin` because that seems like a bug on there end.

Great find regarding the gist token (read not github). Luckily it didn't contain anything sensitive at all. Thanks for the heads up 🎉
